In [1]:
import numpy as np

In [2]:
import time
import sys

To Prove that Numpy Array utilizes less memory compared to Python list

In [3]:
b=range(1000)                   #total memory occupied = (size of a single element * total no of elements)
print(sys.getsizeof(5)*len(b))   

28000


In [4]:
c=np.arange(1000)     # total memory occupied = (total no of elements of the array * size in bytes of each element of the array)
print(c.size*c.itemsize)

4000


Numpy Array is way more faster than Python List in performing any kind of operations

In [5]:
size=100000
L1=range(size)
L2=range(size)
A1=np.arange(size)
A2=np.arange(size)

In [6]:
start=time.time()
result=[(x+y) for x,y in zip(L1,L2)]
print("Python List took:", (time.time()-start)*1000)

Python List took: 15.623092651367188


In [7]:
start=time.time()
result=A1+A2
print("Numpy array took:", (time.time()-start)*1000)

Numpy array took: 1.9996166229248047


# 1-D Array

In [8]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
a[0]

1

In [10]:
arr=np.arange(10)   #widely used arrange function to create 1-D array
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr.shape

(10,)

In [12]:
list1=[12,45,32,99]   #changing list into an array 
arr1=np.array(list1)
arr1

array([12, 45, 32, 99])

In [13]:
print(arr1)              #printing an array

[12 45 32 99]


In [14]:
arr1[2]  #accessimg the value of an array

32

In [15]:
arr1[2]=26   #changing the values of an existing array {arrays are mutable,can change values after creation}
print(arr1)

[12 45 26 99]


# 2-D Array

In [16]:
import numpy as np

In [17]:
arr=np.arange(18).reshape(6,3)   # 'reshape' function is used along with the the 'arange' function for creating a 2-D array
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [18]:
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [19]:
arr1=np.array([[45,23,98],                #another method of creating an array
             [36,21,89]])
arr1

array([[45, 23, 98],
       [36, 21, 89]])

In [20]:
arr[4][2]        #accesing the array element

14

In [21]:
arr[4,2]         #accesing the array element

14

In [22]:
arr1[1][2]=57   #modifying the existing 2-D array element
print(arr1)

[[45 23 98]
 [36 21 57]]


# Attributes of Numpy Array

In [23]:
arr1.ndim      # 1.'ndim': gives the no. of diemensions, of the array as an integer value

2

In [24]:
a.ndim         # for 1-D array its 1 and for 2-D array its 2............for N-D array its N.

1

In [25]:
arr.shape     # 2.'shape': gives the size of an array for each diemension  

(6, 3)

In [26]:
arr1.shape

(2, 3)

In [27]:
a.shape

(3,)

In [28]:
a.size       # 3.'size': gives the total no of elements of the array [product of elements of shape (rows x columns)]

3

In [29]:
arr.size

18

In [30]:
arr.dtype # 4.'dtype': gives the data type of all the elements in the array.Common datatypes are int32, int64,float32,float64,U32.

dtype('int32')

In [31]:
arr1.dtype

dtype('int32')

In [32]:
arr1.itemsize    # 5.'itemsize': specifies the size in bytes of each element of the array

4

In [33]:
a.itemsize     # 8 bits form a byte, thus an array element of type int32 has itemsize of 32/8=4 bytes.

4

# Other Ways of Creating Numpy Arrays

In [34]:
import numpy as np
arr2=np.array([[1,2],[3,4]],dtype=float)  # Specifying the data type while creating the array. 'dtype' as an argument to array
print(arr2)

[[1. 2.]
 [3. 4.]]


In [35]:
arr3=np.zeros((3,4))    #we can create all elements of the array either all of the elements as 0s or all as 1s.
arr4=np.ones((3,2))
print(arr3,arr4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [36]:
arr5=np.arange(6)          #we can create an array with numbers in a given range and sequence using 'arange()' function
arr5

array([0, 1, 2, 3, 4, 5])

In [37]:
arr6=np.arange(-2,24,4)         #creating an array with start value -2 end value 24 and step size 4
arr6

array([-2,  2,  6, 10, 14, 18, 22])

# Reshaping & Resizing an array

In [38]:
b=np.arange(8).reshape(2,4)
print(b)

[[0 1 2 3]
 [4 5 6 7]]


In [39]:
c=b.reshape(2,2,2) 
print(c)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [40]:
np.rollaxis(c, 2, 1)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [41]:
np.rollaxis(c, 1)

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])

In [42]:
np.rollaxis(c, 2)

array([[[0, 2],
        [4, 6]],

       [[1, 3],
        [5, 7]]])

In [43]:
np.rollaxis(c, 1, 2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [44]:
np.swapaxes(c, 1, 2)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [45]:
np.swapaxes(c, 2, 1)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [46]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
print('\n')
b=np.resize(a,(3,2))
print(b)
print(b.shape)
print('\n')
c=np.resize(a,(3,3)) #unlike 'reshape' it won't show any errorthe values will repeat and get adjusted to the the new array size.
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


[[1 2]
 [3 4]
 [5 6]]
(3, 2)


[[1 2 3]
 [4 5 6]
 [1 2 3]]
(3, 3)


# Slicing

In [47]:
import numpy as np

In [48]:
array1=np.array([0,1,2,3,4,5,6,7,8,9])

In [49]:
array1[3:8]   #excludes the value at the eng index

array([3, 4, 5, 6, 7])

In [50]:
array1[::-1]  #reversing the array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [51]:
array1[1:7:2]  #obtain values from index 1 to index 7 (excluding index 7) and skip of 2 interval values

array([1, 3, 5])

for 2-D arrays

In [52]:
arr2=np.array([[-7,4,10,82],           # accessing elements of 1st to 3rd row from 1st and 2nd column
              [-5,1,42,200],        
              [-1,12,4,85]])
print(arr2[0:3,0:2])

[[-7  4]
 [-5  1]
 [-1 12]]


In [53]:
print(arr2[:,2])      # if row indices are not specified, all the row  are to be considered


[10 42  4]


In [54]:
print(arr2[2,:])     # if column indices are not specified, all the columns  are to be considered

[-1 12  4 85]


# Arithemetic operations

In [55]:
a3=np.array([[-7,4,10],           
              [-5,1,42],        
              [-1,12,4]])

a4=np.array([[4,14,-20],           
              [2,1,-32],        
              [16,-17,34]])
x=np.multiply(a3,a4)
print(x)

[[  -28    56  -200]
 [  -10     1 -1344]
 [  -16  -204   136]]


In [56]:
y=np.add(a3,a4)
print(y)

[[ -3  18 -10]
 [ -3   2  10]
 [ 15  -5  38]]


In [57]:
z=np.subtract(a3,a4)
print(z)

[[-11 -10  30]
 [ -7   0  74]
 [-17  29 -30]]


In [58]:
xx=np.divide(a3,a4) #must ensure while dividing a 2-D array with another 2-D array that both the arrays must have same structure
print(xx)           #Also both arrays should not be having any element as zero, otherwise it will raise an error.

[[-1.75        0.28571429 -0.5       ]
 [-2.5         1.         -1.3125    ]
 [-0.0625     -0.70588235  0.11764706]]


# String Functions

In [59]:
print(np.char.multiply('hello ',3))

hello hello hello 


In [60]:
print(np.char.center('hello ',20,fillchar='-'))

-------hello -------


In [61]:
print(np.char.capitalize('hello world'))  #only the first letter of the first word in the statement gets capitalize

Hello world


In [62]:
print(np.char.title('hello james how are you?'))  #each word's first letter gets capitalized

Hello James How Are You?


In [63]:
print(np.char.upper('hellfire has the heat'))        #turns all the characters to upper case

HELLFIRE HAS THE HEAT


In [64]:
print(np.char.lower('YOU JUST GONNA GET BACKUP'))   #turns all the characters to lower case

you just gonna get backup


In [65]:
print(np.char.split('are you coming to the party'))   #splits each words of the statement individually on the space basis

['are', 'you', 'coming', 'to', 'the', 'party']


In [66]:
print(np.char.splitlines('are you \n coming to the party'))    #splitting on the basis of lines

['are you ', ' coming to the party']


In [67]:
print(np.char.strip(['aman','aditya','ankita'],'a'))   #removes all the leading and trailling 'a' from the words

['man' 'dity' 'nkit']


In [68]:
print(np.char.join([':','-'],['dmy','ymd']))    #splits up the l;etters by ':' and '-'

['d:m:y' 'y-m-d']


In [69]:
print(np.char.replace('He is a good dancer','is','was'))      #replacing the words

He was a good dancer


In [70]:
print('concatenation example')
print(np.char.add(['hello ','hi'],['abc',' xyz']))

concatenation example
['hello abc' 'hi xyz']


# Transpose

Transposing an array turns its rows into columns and columns into rows. 

In [71]:
arr3=np.array([[4,14,-20],           
              [2,1,-32],        
              [16,-17,34]])
arr3.transpose()

array([[  4,   2,  16],
       [ 14,   1, -17],
       [-20, -32,  34]])

In [72]:
arr3                   #The original array does not change

array([[  4,  14, -20],
       [  2,   1, -32],
       [ 16, -17,  34]])

# Sorting

Method to arrange the elements of an array in hiearchial order either ascending or descending.
By default its in Ascending order.

In [73]:
arr3.sort()         #row-wise sorting      for column-wise axis=0, row-wise axis=1-->(by default)
arr3

array([[-20,   4,  14],
       [-32,   1,   2],
       [-17,  16,  34]])

In [74]:
arr3.sort(axis=0)         #column-wise sorting
arr3

array([[-32,   1,   2],
       [-20,   4,  14],
       [-17,  16,  34]])

# Concatenating Arrays

In [75]:
a=np.array([[1,2],[3,4]])
print('First Array')
print(a)
print('\n')
b=np.array([[5,6],[7,8]])
print('Second Array')
print(b)

First Array
[[1 2]
 [3 4]]


Second Array
[[5 6]
 [7 8]]


All input array diemensions except for the concatenation axis must match exactly.

In [76]:
print(np.concatenate((a,b)))               #joining arrays along column elements i.e. addition of new rows
print('\n')
print(np.concatenate((a,b), axis=1))       #joining arrays along row elements i.e. addition of new columns

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[1 2 5 6]
 [3 4 7 8]]


In [77]:
import numpy as np
print('concatenation example')
print(np.char.add(['hello ','hi'],['abc',' xyz']))

concatenation example
['hello abc' 'hi xyz']


# Iterating over Array

In [78]:
p=np.arange(0,45,5)           #creating a 1-D array
p=p.reshape(3,3)              #converting it to 2D-array-
print(p)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]]


In [79]:
for x in np.nditer(p):
    print(x)

0
5
10
15
20
25
30
35
40


In [80]:
print(p.flatten())           #restores back the (3,3) array back into its original form 

[ 0  5 10 15 20 25 30 35 40]


# Iteration order C-style, F-style

In [81]:
print(p)
print('\n') 
for x in np.nditer(p, order="C"):          # each row-wise element extracting
    print(x)
print('\n')    
for x in np.nditer(p, order="F"):          # each column-wise element extracting
    print(x)
print('\n')     
for x in np.nditer(p, order="A"):          # order/sequemce-wise element extracting
    print(x)    

[[ 0  5 10]
 [15 20 25]
 [30 35 40]]


0
5
10
15
20
25
30
35
40


0
15
30
5
20
35
10
25
40


0
5
10
15
20
25
30
35
40


In [82]:
print(p.flatten( order="C"))   #row major (C)     By default its C .....

[ 0  5 10 15 20 25 30 35 40]


In [83]:
print(p.flatten( order="F"))   #column-major (Fortran)

[ 0 15 30  5 20 35 10 25 40]


In [84]:
print(p.flatten( order="A"))   #preserve the C/Fortran order ....in regular manner

[ 0  5 10 15 20 25 30 35 40]


# Splitting the array

In [85]:
c=np.arange(9)
np.split(c,3)         #splitting into 3 parts

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [86]:
np.split(c,[3,6,8])   #splitting the array at intervals at indices 3,6 and 8

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8])]

In [87]:
np.split(c,[2,6])     #splitting the array at intervals at indices 2 and 6

[array([0, 1]), array([2, 3, 4, 5]), array([6, 7, 8])]

In [88]:
y=np.array([[10,-7,20,20],
      [-5,1,200,40],
       [30,1,-1,37],
       [42,21,0,4],
       [0,1,12,2]])
print(y)

[[ 10  -7  20  20]
 [ -5   1 200  40]
 [ 30   1  -1  37]
 [ 42  21   0   4]
 [  0   1  12   2]]


In [89]:
np.split(y,[1,3])    #splitting is on the basis of row indices    by default  axis=0

[array([[10, -7, 20, 20]]),
 array([[ -5,   1, 200,  40],
        [ 30,   1,  -1,  37]]),
 array([[42, 21,  0,  4],
        [ 0,  1, 12,  2]])]

In [90]:
np.split(y,[2,3],axis=1)     #splitting is on the basis of column indices 

[array([[10, -7],
        [-5,  1],
        [30,  1],
        [42, 21],
        [ 0,  1]]),
 array([[ 20],
        [200],
        [ -1],
        [  0],
        [ 12]]),
 array([[20],
        [40],
        [37],
        [ 4],
        [ 2]])]

In [91]:
np.split(y,2,axis=1)    #splitting into two equal no of columns

[array([[10, -7],
        [-5,  1],
        [30,  1],
        [42, 21],
        [ 0,  1]]),
 array([[ 20,  20],
        [200,  40],
        [ -1,  37],
        [  0,   4],
        [ 12,   2]])]